<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>@yield('title')</title>

        <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
        <script type="application/ld+json">
        {
          "@context" : "http://schema.org",
          "@type" : "LocalBusiness",
          "name" : "Taylor Properties",
          "image" : "http://www.helpshop.com/c/wp-content/uploads/2010/12/tpLogo-590x417.jpg",
          "telephone" : "800-590-0925",
          "address" : {
            "@type" : "PostalAddress",
            "streetAddress" : "175 Admiral Cochrane Drive, Suite 112",
            "addressLocality" : "Annapolis",
            "addressRegion" : "MD",
            "postalCode" : "21401"
          },
          "openingHoursSpecification" : {
            "@type" : "OpeningHoursSpecification",
            "dayOfWeek" : {
              "@type" : "DayOfWeek",
              "name" : "Monday - Friday"
            }
          },
          "url" : "www.taylorproperties.co"
        }
        </script>

        <link rel="shortcut icon" href="{{ asset('favicon.png') }}">
		<link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
		<link rel="stylesheet" href="{{ asset('css/app.css') }}">
    </head>
    <body>
    	@yield('content')
    </body>
</html>