<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSRF Token -->
		<meta name="csrf-token" content="{{ csrf_token() }}">

        <title>@yield('title')</title>

        <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
        <script type="application/ld+json">
        {
          "@context" : "http://schema.org",
          "@type" : "LocalBusiness",
          "name" : "Taylor Properties",
          "image" : "http://www.helpshop.com/c/wp-content/uploads/2010/12/tpLogo-590x417.jpg",
          "telephone" : "800-590-0925",
          "address" : {
            "@type" : "PostalAddress",
            "streetAddress" : "175 Admiral Cochrane Drive, Suite 112",
            "addressLocality" : "Annapolis",
            "addressRegion" : "MD",
            "postalCode" : "21401"
          },
          "openingHoursSpecification" : {
            "@type" : "OpeningHoursSpecification",
            "dayOfWeek" : {
              "@type" : "DayOfWeek",
              "name" : "Monday - Friday"
            }
          },
          "url" : "www.taylorproperties.co"
        }
        </script>

        <link rel="shortcut icon" href="{{ asset('favicon.png') }}">
		<link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
		<link rel="stylesheet" href="{{ asset('css/app.css') }}">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
		
    </head>
    <body>
    	@include('includes.navbar')

   		@yield('content')

    	<!-- Scripts -->
    	<script src="{{ asset('js/app.js') }}"></script>
    </body>

    @include('includes.footer')
</html>