<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSRF Token -->
		    <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>@yield('title')</title>
        <meta name="Description" content="Taylor Properties offers residential and commercial Real Estate services throughout Maryland, DC and Virginia. As one of the fastest growing Brokerages we have agents to cover any of you home buying needs from foreclosures to water front.">
        <meta name="Keywords" content="taylor properties, Real Estate Agents maryland, real estate company maryland, real estate agents maryland">

        <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
        <script type="application/ld+json">
        {
          "@context" : "http://schema.org",
          "@type" : "LocalBusiness",
          "name" : "Taylor Properties",
          "image" : "{{ asset('images/logos/TaylorProperties-horizontal-fullcolor.png') }}",
          "telephone" : "800-590-0925",
          "address" : {
            "@type" : "PostalAddress",
            "streetAddress" : "175 Admiral Cochrane Drive, Suite 112",
            "addressLocality" : "Annapolis",
            "addressRegion" : "MD",
            "postalCode" : "21401"
          },
          "openingHoursSpecification" : {
            "@type" : "OpeningHoursSpecification",
            "dayOfWeek" : {
              "@type" : "DayOfWeek",
              "name" : "Monday - Friday"
            }
          },
          "url" : "www.taylorproperties.co"
        }
        </script>

        <link rel="shortcut icon" href="{{ asset('favicon.png') }}">
    		<link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
    		<link rel="stylesheet" href="{{ asset('css/app.css') }}">
    		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
		    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </head>
    <body>
    	@include('includes.navbar')

   		@yield('content')

      @include('includes.featured_listings')

    	<!-- Scripts -->
    	<script src="{{ asset('js/app.js') }}"></script>
    </body>

    @include('includes.footer')
</html>